### ISSUE TITLE
billiard package version not handled correctly

### ISSUE THREAD

**Issue by gdub** [sesh/piprot#42]
Perhaps due to the fact that billiard uses a 4-part version number?

The latest version of billiard is currently 3.3.0.20:
https://pypi.python.org/pypi/billiard/3.3.0.20

With a requirements file containing:
```
billiard==3.3.0.20
```
...multiple runs of piprot produce various, conflicting outputs:
```
$ piprot 
billiard (3.3.0.20) is out of date. Latest is 3.3.0.2
Looks like you've been keeping up to date, time for a delicious beverage!

$ piprot 
billiard (3.3.0.20) is out of date. Latest is 3.3.0.15
Looks like you've been keeping up to date, time for a delicious beverage!

$ piprot 
billiard (3.3.0.20) is out of date. Latest is 3.3.0.1
Looks like you've been keeping up to date, time for a delicious beverage!
```

**Comment by sesh** [comment]
Sorry I missed this one!

Weird!

I'll look into this over the weekend. Looks like a real issue from my quick tests.

**Comment by sekrause** [comment]
Two more packages that it tries to downgrade:

```
py2exe==0.9.2.2
regex==2014.12.24
```

This is the result:

```
py2exe (0.9.2.2) is out of date. Latest is 0.9.2.0
regex (2014.12.24) is out of date. Latest is 2013-12-31
Looks like you've been keeping up to date, time for a delicious beverage!
```

**Comment by sesh** [comment]
This took a couple of weeks longer than I thought, but should be sorted out now!
