### ISSUE TITLE
Accept a wider range of specifiers

### ISSUE THREAD

**Issue by kvdb** [sesh/piprot#43]
This is a line from my dev-requirements.txt:

```
behave ~= 1.2.5
```

It's legal according to:
https://pip.pypa.io/en/latest/reference/pip_install.html#requirement-specifiers
However, piprot just skips over it.

I locally applied the following local fix improving the situation a bit:

```
--- a/piprot/piprot.py
+++ b/piprot/piprot.py
@@ -110,7 +110,7 @@ def parse_req_file(req_file, verbatim=False):
         requirement_no_comments = requirement.split('#')[0].strip()

         # if matching requirement line (Thing==1.2.3), update dict, continue
-        req_match = re.match(r'\s*(?P<package>\S+)==(?P<version>\S+)',
+        req_match = re.match(r'\s*(?P<package>\S+)\s*[~=>]=\s*(?P<version>\S+)',
                              requirement_no_comments)
         if req_match:
             req_list.append((req_match.group('package'),
```

**Comment by sesh** [comment]
@kvdb thanks! :+1:

PR welcome on this one, otherwise I'll look into it in the next few days (i.e. on the weekend)

**Comment by murphyke** [comment]
Yes, piprot should handle inequalities, like:

    loxun<1.4

**Comment by sedrubal** [comment]
:+1: ;)
