### ISSUE TITLE
Interactive piprot

### ISSUE THREAD

**Issue by pquentin** [sesh/piprot#44]
Is it possible to add a `--interactive` flag? This would ask the user if he wants to upgrade the outdated package. If yes, it would do it with `pip install -U`. This is what pip-review from pip-tools used to do before it got removed from pip-tools.

**Comment by sesh** [comment]
@pquentin Interesting.

I'd be interested in a PR for this, but might not have time to investigate developing it quickly. I'll add it to the list of potential features though!
