### ISSUE TITLE
Add a webservice

### ISSUE THREAD

**Issue by sedrubal** [sesh/piprot#55]
Do you wan't to create a webservice similar to https://requires.io/? I think, it's quite useful to have badges and integration in github API, but requires.io needs write access to repositories and organizations. :(

**Comment by sesh** [comment]
@sedrubal this was my take on a CLI driven version of something similar to requires.io. The requirement to sign in with Github and give away read / write access to everything was a deal breaker for me as well.

https://piprot.io/

**Comment by sedrubal** [comment]
great :D but I miss the badges a bit :smile:

**Comment by sedrubal** [comment]
don't you want to inter agate with the github API so that pull requests and commits can be checked like these [integrations](https://github.com/integrations) do it?

**Comment by sesh** [comment]
I do, but it's a different product that what `piprot` is - I'd like to keep this as a simple CLI to check your requirements files..

People are already able to integrate it into their own CI solution to run the check every time they commit.

Plus, requires.io already does a perfectly good job of this usecase.

**Comment by sedrubal** [comment]
ok...
