### ISSUE TITLE
Failure when using `-r requirements2.txt` in requirements

### ISSUE THREAD

**Issue by wcooley** [sesh/piprot#57]
`pip` supports having `-r requirements2.txt` in the `requirements.txt`, which I use to build cascading environment requirements, e.g., `develop.txt` has `-r test.txt` and `test.txt` has `-r deploy.txt`. Unfortunately, as of 0.9.5, `piprot` barfs on these:

```
$ piprot - < requirements/develop.txt
Traceback (most recent call last):
  File ".../bin/piprot", line 11, in <module>
    sys.exit(piprot())
  File ".../lib/python3.3/site-packages/piprot/piprot.py", line 494, in piprot
    url=cli_args.url)
  File ".../lib/python3.3/site-packages/piprot/piprot.py", line 262, in main
    requirements.extend(parse_req_file(req_file, verbatim=verbatim))
  File ".../lib/python3.3/site-packages/piprot/piprot.py", line 132, in parse_req_file
    file_name = requirement_no_comments.split(' ')[1]
IndexError: list index out of range
```

If I filter these lines out, it works fine:

```
$ piprot - < <(grep -vE '^-' requirements/develop.txt )
Looks like you've been keeping up to date, time for a delicious beverage!
```

Hm, it looks like the real problem is that I have `-rfoo.txt`, but line 132 assumes there is space between the `-r` and `foo.txt`. I have to wonder if, instead of writing an _ad hoc_ requirements parser, it wouldn't be better to use `pip.req.req_file.parse_requirements()`.

**Comment by sesh** [comment]
@wcooley thanks for the report.

I've actually been meaning to revamp a large portion of the requirements parsing (and version comparison) code to use the functions from `pip` itself. Unfortunately I haven't gotten around to it (and supporting the various versions of pip and setup tools in the wild looks like an interesting challenge.

For now, I'd be happy to add support for `-rrequirements.txt` lines.
