### ISSUE TITLE
with gunicorn==19.4 specified, version 19.4.5 is not suggested as newer

### ISSUE THREAD

**Issue by gdub** [sesh/piprot#61]
I presume it has something to do with the fact that there are a different number of version spec parts, but I haven't tested any other packages.

```
$ echo "gunicorn==19.4" > req.txt
$ piprot req.txt 
Looks like you've been keeping up to date, time for a delicious beverage!
```

```
$ echo "gunicorn==19.4.1" > req.txt
$ piprot req.txt 
gunicorn (19.4.1) is 40 days out of date. Latest is 19.4.5
Your requirements are 40 days out of date
```

**Comment by sesh** [comment]
Thanks for the bug report @gdub, will check this out over the next few days when I get a chance.

**Comment by gdub** [comment]
This issue is still present in latest piprot version (0.9.7).
